### ISSUE TITLE
转换失败

### ISSUE THREAD

**Issue by dddddl** [LucasDevelop/LangTransExcel#1]
Error:The supplied data appears to be in the Office 2007+ XML. You are calling the part of POI that deals with OLE2 Office Documents. You need to call a different part of POI to process this data (eg XSSF instead of HSSF)

**Comment by LucasDevelop** [comment]
https://github.com/LucasDevelop/LangTransExcel/blob/master/LangTransExcel-V1.0.1.zip

**Comment by LucasDevelop** [comment]
已更新版本，请尝试安装新版，已支持所有excel版本
